### PR TITLE
Fix editor export

### LINKED ISSUE #2768: Model editor : empty snippet
### Discussed in https://github.com/google/model-viewer/discussions/2767

<div type='discussions-op-text'>

<sup>Originally posted by **MintyP** September  9, 2021</sup>
Hello everyone !

I use the model editor (https://modelviewer.dev/editor/) to upload my glb files, edit the scene and download a zip to integrate in my website (to have a model viewer directly on it).
I recently had a new issue : the zip files doesn't work on my website anymore and I noticed that when I click on "download scene", I get a zip file with an empty snippet.
I tried replacing the empty snippet with one that I know works, but no result... I get this issue with any glb I upload or take from the library.

You'll get from this that I'm not really familiar with coding nor github, sorry for this.

Thanks !</div>

### PR DESCRIPTION
**Pull request by elalish**
Fixes #2768 / #2767

I must have moved an element when I was refactoring  that I shouldn't have. I also made the snippet non-sticky, which makes the editor much more usable on mobile.

I was  surprised to find there was no test  for this, but I  tried adding one and now  I think I know why. When adding a  test for the snippet, the download button is part of  that, which imports `JSZip`, a commonJS module with a default export. It all works with rollup, but Karma chokes on it  with a  pretty baffling error message. I  tried a bunch of things, but could not get  it to resolve the import, so I'm punting on that test for now.

### CODE REVIEW

File: packages/space-opera/src/components/model_viewer_snippet/model_viewer_snippet.ts [hunk 1]
```diff
@@ -45,7 +45,7 @@ import {applyRelativeFilePaths, getExtraAttributes} from './reducer.js';
  */
 @customElement('me-export-panel')
 export class ExportPanel extends ConnectedLitElement {
-  @property({type: String}) header = '';
+  @property({type: Boolean}) header = false;
```
Comment (timmmeh) [inline packages/space-opera/src/components/model_viewer_snippet/model_viewer_snippet.ts:48]: Dumb question, what is header used for in ExportPanel?

**Review by timmmeh — APPROVED** [review]

File: packages/space-opera/src/components/model_viewer_snippet/model_viewer_snippet.ts (hunk 1 above)
Comment (elalish) [reply packages/space-opera/src/components/model_viewer_snippet/model_viewer_snippet.ts:48]: It's the snippet-only section that's shown in the edit and camera tabs. This whole chunk of code is  quite  confusing to me; I tried to refactor it, but it was becoming too large a change to be worthwhile just now.
