### PR TITLE
Adding fix for alpha test issue #2931

### LINKED ISSUE #2931: Materials setAlphaMode appears to apply MASK instead of BLEND
### Description

Setting alpha mode to 'BLEND' on any material with alpha < 0.5 makes the material invisible (as though it was masked)

Correct with v1.8.0:
image

Wrong with v1.9.0:
image

Model Viewer version 1.8.0 works fine.

#### Live Demo

https://glitch.com/edit/#!/fluffy-skitter-move

### Version
- model-viewer: v1.9.0

### Browser Affected

- [x] Chrome, version: 95.0.4638.54
- [x] Firefox 93.0
- [x] Safari 15.1, previous versions affected too
- [x] Brave 1.30.89 

### OS

- [x] Linux
- [x] MacOS
- [x] Windows

### AR
Not applicable

### PR DESCRIPTION
**Pull request by timmmeh**
Adding fix for alpha test

Fixes #2931

### CODE REVIEW

File: packages/model-viewer/src/features/scene-graph/material.ts [hunk 1]
```diff
@@ -238,7 +238,11 @@ export class Material extends ThreeDOMElement implements MaterialInterface {
     const gltfMaterial = this[$sourceObject] as DefaultedMaterial;
     for (const material of this[$correlatedObjects] as
          Set<MeshStandardMaterial>) {
-      material.alphaTest = gltfMaterial.alphaCutoff;
+      if ((this[$sourceObject] as DefaultedMaterial).alphaMode === 'MASK') {
+        material.alphaTest = gltfMaterial.alphaCutoff;
+      } else {
+        material.alphaTest = 0;
```
Comment (elalish) [inline packages/model-viewer/src/features/scene-graph/material.ts:244]: This feels  like a hack to me; I don't think `alphaTest` should even  be used  by the shader  if  the mode is really set to `MASK`. I'd  guess something is wrong with setting the blend mode. Have you looked at what GLTFLoader does when it gets these different materials as input?

Comment (timmmeh) [reply packages/model-viewer/src/features/scene-graph/material.ts:244]: `material.alphaTest = 0;` was because I was paranoid, looks like it's not needed.

**Comment by timmmeh** [comment]
@elalish the failing fidelity test has nothing to do with this change, it's occurring on the other PR too, it looks like we are producing the correct output, I think out golden is incorrect. It looks like the golden is actually matching the `incorrect.png` file from glTF-Sample-Models-master/2.0/TextureLinearInterpolationTest/screenshot

File: packages/model-viewer/src/features/scene-graph/material.ts (hunk 1 above)
Comment (elalish) [reply packages/model-viewer/src/features/scene-graph/material.ts]: Hmm, looking at three's code I think you were actually on the right track, except they base their logic on its presence: https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLProgram.js#L637

Looks like  you need  to set it to undefined instead of zero.

**Review by elalish — CHANGES_REQUESTED** [review]
Yeah, I'll look into the fidelity test  thing. You've  pulled master recently right?

**Review by elalish — APPROVED** [review]
Thanks!

File: packages/model-viewer/src/features/scene-graph/material.ts [hunk 2]
```diff
@@ -238,7 +238,12 @@ export class Material extends ThreeDOMElement implements MaterialInterface {
     const gltfMaterial = this[$sourceObject] as DefaultedMaterial;
     for (const material of this[$correlatedObjects] as
          Set<MeshStandardMaterial>) {
-      material.alphaTest = gltfMaterial.alphaCutoff;
+      if ((this[$sourceObject] as DefaultedMaterial).alphaMode === 'MASK') {
+        material.alphaTest = gltfMaterial.alphaCutoff;
+      } else {
+        (material.alphaTest as number | undefined) = undefined;
```
Comment (elalish) [inline packages/model-viewer/src/features/scene-graph/material.ts:244]: Let's make a  note to update the  three.js types repo for  this.
