### PR TITLE
fixed multiple webXR issues

### LINKED ISSUE #1190: Problems with multiple webXR demos on one page
When entering webXR mode with the second object on this [Glitch](https://model-viewer-blog.glitch.me/), the annotations disappear. When exiting webXR, the object is not properly centered.

### PR DESCRIPTION
**Pull request by elalish**
Fixes #1190 

The first problem was caused by a line of code I didn't write, but I'm ashamed I read it so many times without noticing the fairly glaring error. The second problem was that we were failing to call resize when cleaning up webXR. I think I missed this because our examples all use a %width CSS which causes the resize observer to fire when leaving fullscreen, but it does not for fixed-width elements.

### CODE REVIEW

File: packages/model-viewer/src/three-components/ARRenderer.ts [hunk 1]
```diff
@@ -150,8 +150,8 @@ export class ARRenderer extends EventDispatcher {
           requiredFeatures: ['hit-test'],
           optionalFeatures: ['dom-overlay'],
           domOverlay: {
-            root: document.querySelector('model-viewer')!.shadowRoot!
-                      .querySelector('div.annotation-container')
```
Comment (cdata) [inline packages/model-viewer/src/three-components/ARRenderer.ts:154]: 😳
