### PR TITLE
fix #5026 issue and refactor ModelScene.ts

### LINKED ISSUE #5026: Backwards animation does not work anymore since model-viewer 4.1.0 release
### Description
Since the upgrade to model-viewer 4.1.0, animations with a negative `timeScale` (playing in reverse) no longer function correctly. This worked properly in version 4.0.0.

### Expected Behavior
The animation should play in reverse (from end to start).

### Actual Behavior
The animation does not play when `timeScale` is negative.

### Reproduction
I've created a JSFiddle that demonstrates the issue: https://jsfiddle.net/d8r2bmqL/. You can change the model-viewer version from 4.1.0 to 4.0.0 to see that backwards animation worked correctly in the previous version.

The demo uses the `RobotExpressive.glb` model with the "Death" animation. When clicking the play button, it should alternate between playing forward and backward.

### Possible Cause
I believe the issue may be related to the following code:

https://github.com/google/model-viewer/blob/4efaf8eebb8a9b48080b87faa39faa544a728f92/packages/model-viewer/src/three-components/ModelScene.ts#L756-L759

Commenting out this code makes the backwards animation work again. I'm not entirely sure why this code was implemented in the first place, but it appears to be causing the reverse animation functionality to break in version 4.1.0.

@mohammadbaghaei  - Since you worked on the animation code for 4.1.0. Would you have time to take a look at this issue? Your expertise would be appreciated in understanding why this behavior changed and how we can restore the backward animation functionality.

### Environment
- model-viewer version: 4.1.0
- Browser: Firefox 137.0.1 (also reproduced on Chrome)
- Operating System: macOS (also reproduced on Windows)

### PR DESCRIPTION
**Pull request by mohammadbaghaei**

### CODE REVIEW

File: packages/model-viewer/src/three-components/ModelScene.ts [hunk 1]
```diff
@@ -13,22 +13,22 @@
...
+import ModelViewerElementBase, { $renderer, $scene, EffectComposerInterface, RendererInterface } from '../model-viewer-base.js';
+import { ModelViewerElement } from '../model-viewer.js';
+import { normalizeUnit } from '../styles/conversions.js';
+import { NumberNode, parseExpressions } from '../styles/parsers.js';
+
+import { Damper, SETTLING_TIME } from './Damper.js';
+import { ModelViewerGLTFInstance } from './gltf-instance/ModelViewerGLTFInstance.js';
+import { GroundedSkybox } from './GroundedSkybox.js';
+import { Hotspot } from './Hotspot.js';
+import { Shadow } from './Shadow.js';
```
Comment (diegoteran) [inline packages/model-viewer/src/three-components/ModelScene.ts]: extra spaces everywhere
